name: weather_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  flutter_multi_formatter: ^2.13.7
  units_converter: ^3.0.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
